<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\AboutPageSection;

class AboutPageSectionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Vision & Mission Page Sections
        $visionMissionSections = [
            [
                'page_slug' => 'vision-mission',
                'section_key' => 'vision',
                'title' => 'Our Vision',
                'subtitle' => "To be Africa's premier distance-learning institution",
                'description' => "Transforming education through innovative distance learning, cutting-edge research, and technology-driven excellence to create sustainable solutions for Africa's development challenges.",
                'icon' => 'Eye',
                'color' => 'from-blue-500 to-blue-600',
                'items' => ['Distance Learning Excellence', 'Research Innovation', 'Technology Leadership', 'Pan-African Impact'],
                'sort_order' => 1,
                'is_active' => true,
            ],
            [
                'page_slug' => 'vision-mission',
                'section_key' => 'mission',
                'title' => 'Our Mission',
                'subtitle' => 'Empowering minds across Africa through distance education',
                'description' => 'To provide accessible quality education through distance learning, foster cutting-edge research, and develop leaders who will drive positive change across Africa and beyond.',
                'icon' => 'Target',
                'color' => 'from-green-500 to-green-600',
                'items' => ['Accessible Education', 'Research Excellence', 'Leadership Development', 'Digital Innovation'],
                'sort_order' => 2,
                'is_active' => true,
            ],
            [
                'page_slug' => 'vision-mission',
                'section_key' => 'achievement',
                'title' => 'Academic Awards',
                'subtitle' => '200+',
                'description' => 'Recognition for excellence',
                'icon' => 'Trophy',
                'color' => 'from-yellow-400 to-orange-500',
                'sort_order' => 3,
                'is_active' => true,
            ],
            [
                'page_slug' => 'vision-mission',
                'section_key' => 'achievement',
                'title' => 'African Countries',
                'subtitle' => '50+',
                'description' => 'Pan-African reach',
                'icon' => 'Globe',
                'color' => 'from-blue-400 to-indigo-500',
                'sort_order' => 4,
                'is_active' => true,
            ],
            [
                'page_slug' => 'vision-mission',
                'section_key' => 'achievement',
                'title' => 'Research Publications',
                'subtitle' => '1000+',
                'description' => 'Academic contributions',
                'icon' => 'Microscope',
                'color' => 'from-purple-400 to-pink-500',
                'sort_order' => 5,
                'is_active' => true,
            ],
            [
                'page_slug' => 'vision-mission',
                'section_key' => 'achievement',
                'title' => 'Distance Learners',
                'subtitle' => '100K+',
                'description' => 'Students worldwide',
                'icon' => 'Users',
                'color' => 'from-green-400 to-emerald-500',
                'sort_order' => 6,
                'is_active' => true,
            ],
            [
                'page_slug' => 'vision-mission',
                'section_key' => 'timeline',
                'title' => 'University Founded',
                'subtitle' => '2008',
                'description' => 'Established as a leading private distance-learning institution committed to excellence',
                'sort_order' => 7,
                'is_active' => true,
            ],
            [
                'page_slug' => 'vision-mission',
                'section_key' => 'timeline',
                'title' => 'First Programs Launched',
                'subtitle' => '2010',
                'description' => 'Introduced innovative distance learning programs across Africa',
                'sort_order' => 8,
                'is_active' => true,
            ],
            [
                'page_slug' => 'vision-mission',
                'section_key' => 'timeline',
                'title' => 'Research Excellence',
                'subtitle' => '2014',
                'description' => 'Achieved international recognition for research and innovation',
                'sort_order' => 9,
                'is_active' => true,
            ],
            [
                'page_slug' => 'vision-mission',
                'section_key' => 'timeline',
                'title' => 'Digital Transformation',
                'subtitle' => '2018',
                'description' => 'Implemented cutting-edge online learning technologies',
                'sort_order' => 10,
                'is_active' => true,
            ],
            [
                'page_slug' => 'vision-mission',
                'section_key' => 'timeline',
                'title' => 'Pan-African Expansion',
                'subtitle' => '2022',
                'description' => 'Expanded reach across 50+ African countries',
                'sort_order' => 11,
                'is_active' => true,
            ],
            [
                'page_slug' => 'vision-mission',
                'section_key' => 'timeline',
                'title' => 'Global Leadership',
                'subtitle' => '2026',
                'description' => 'Leading the future of distance education in Africa',
                'sort_order' => 12,
                'is_active' => true,
            ],
            [
                'page_slug' => 'vision-mission',
                'section_key' => 'core_value',
                'title' => 'Excellence',
                'description' => 'We strive for academic and professional excellence in all our endeavors',
                'icon' => 'Heart',
                'color' => 'from-pink-500 to-rose-600',
                'sort_order' => 13,
                'is_active' => true,
            ],
            [
                'page_slug' => 'vision-mission',
                'section_key' => 'core_value',
                'title' => 'Integrity',
                'description' => 'We uphold the highest ethical standards in our conduct and relationships',
                'icon' => 'Users',
                'color' => 'from-blue-500 to-cyan-600',
                'sort_order' => 14,
                'is_active' => true,
            ],
            [
                'page_slug' => 'vision-mission',
                'section_key' => 'core_value',
                'title' => 'Innovation',
                'description' => 'We foster creativity and innovative thinking to solve real-world challenges',
                'icon' => 'Lightbulb',
                'color' => 'from-yellow-500 to-orange-600',
                'sort_order' => 15,
                'is_active' => true,
            ],
            [
                'page_slug' => 'vision-mission',
                'section_key' => 'core_value',
                'title' => 'Impact',
                'description' => 'We create meaningful change through education, research, and community service',
                'icon' => 'Target',
                'color' => 'from-green-500 to-emerald-600',
                'sort_order' => 16,
                'is_active' => true,
            ],
        ];

        // Who We Are Page Sections
        $whoWeAreSections = [
            [
                'page_slug' => 'who-we-are',
                'section_key' => 'vc_message',
                'title' => 'Message from the Vice Chancellor',
                'subtitle' => 'Welcome to University of Africa',
                'description' => "Welcome to University of Africa. As we embark on this exciting chapter in our institution's growth, I am delighted to invite you to join a community dedicated to transformative learning and meaningful impact across Africa and beyond. The University of Africa stands at a critical moment in African higher education. We are committed to developing the next generation of scholars, leaders, and practitioners who will address the continent's most pressing challenges through evidence-based professional practice, research, and ethical leadership.",
                'icon' => 'User',
                'sort_order' => 0,
                'is_active' => true,
            ],
            [
                'page_slug' => 'who-we-are',
                'section_key' => 'stat',
                'title' => 'Students Worldwide',
                'subtitle' => '45M+',
                'icon' => 'GraduationCap',
                'color' => 'from-blue-500 to-blue-600',
                'sort_order' => 1,
                'is_active' => true,
            ],
            [
                'page_slug' => 'who-we-are',
                'section_key' => 'stat',
                'title' => 'Countries',
                'subtitle' => '50+',
                'icon' => 'Globe',
                'color' => 'from-green-500 to-green-600',
                'sort_order' => 2,
                'is_active' => true,
            ],
            [
                'page_slug' => 'who-we-are',
                'section_key' => 'stat',
                'title' => 'Programs',
                'subtitle' => '200+',
                'icon' => 'BookOpen',
                'color' => 'from-purple-500 to-purple-600',
                'sort_order' => 3,
                'is_active' => true,
            ],
            [
                'page_slug' => 'who-we-are',
                'section_key' => 'stat',
                'title' => 'Awards',
                'subtitle' => '200+',
                'icon' => 'Trophy',
                'color' => 'from-yellow-500 to-yellow-600',
                'sort_order' => 4,
                'is_active' => true,
            ],
            [
                'page_slug' => 'who-we-are',
                'section_key' => 'feature',
                'title' => 'Fast-Track Education',
                'description' => "Upgrade your diploma to bachelor's degree within 2 years",
                'icon' => 'Rocket',
                'color' => 'from-orange-500 to-red-500',
                'sort_order' => 5,
                'is_active' => true,
            ],
            [
                'page_slug' => 'who-we-are',
                'section_key' => 'feature',
                'title' => 'Flexible Learning',
                'description' => 'Study at your own pace with continuous registration year-round',
                'icon' => 'Clock',
                'color' => 'from-blue-500 to-cyan-500',
                'sort_order' => 6,
                'is_active' => true,
            ],
            [
                'page_slug' => 'who-we-are',
                'section_key' => 'feature',
                'title' => 'Affordable Excellence',
                'description' => 'Quality education with scholarships and flexible payment systems',
                'icon' => 'Heart',
                'color' => 'from-green-500 to-emerald-500',
                'sort_order' => 7,
                'is_active' => true,
            ],
            [
                'page_slug' => 'who-we-are',
                'section_key' => 'feature',
                'title' => 'Fully Accredited',
                'description' => 'Recognized qualifications from diploma to doctorate levels',
                'icon' => 'Award',
                'color' => 'from-purple-500 to-pink-500',
                'sort_order' => 8,
                'is_active' => true,
            ],
            [
                'page_slug' => 'who-we-are',
                'section_key' => 'value',
                'title' => 'African Pride',
                'description' => 'Proudly serving the African continent',
                'icon' => 'Flag',
                'sort_order' => 9,
                'is_active' => true,
            ],
            [
                'page_slug' => 'who-we-are',
                'section_key' => 'value',
                'title' => 'Simplicity',
                'description' => 'Effective yet simple service delivery',
                'icon' => 'Shield',
                'sort_order' => 10,
                'is_active' => true,
            ],
            [
                'page_slug' => 'who-we-are',
                'section_key' => 'value',
                'title' => 'Modern Approach',
                'description' => 'Digital learning innovation',
                'icon' => 'Zap',
                'sort_order' => 11,
                'is_active' => true,
            ],
            [
                'page_slug' => 'who-we-are',
                'section_key' => 'value',
                'title' => 'Excellence',
                'description' => 'Standing out in quality and impact',
                'icon' => 'Star',
                'sort_order' => 12,
                'is_active' => true,
            ],
            [
                'page_slug' => 'who-we-are',
                'section_key' => 'affiliation',
                'title' => 'CIRSM Zimbabwe',
                'subtitle' => 'Zimbabwe',
                'sort_order' => 13,
                'is_active' => true,
            ],
            [
                'page_slug' => 'who-we-are',
                'section_key' => 'affiliation',
                'title' => 'RIME Zimbabwe',
                'subtitle' => 'Zimbabwe',
                'sort_order' => 14,
                'is_active' => true,
            ],
            [
                'page_slug' => 'who-we-are',
                'section_key' => 'affiliation',
                'title' => 'Workers University College',
                'subtitle' => 'Eswatini',
                'sort_order' => 15,
                'is_active' => true,
            ],
            [
                'page_slug' => 'who-we-are',
                'section_key' => 'affiliation',
                'title' => 'Empirical Academy',
                'subtitle' => 'South Africa',
                'sort_order' => 16,
                'is_active' => true,
            ],
            [
                'page_slug' => 'who-we-are',
                'section_key' => 'affiliation',
                'title' => 'SAIHER',
                'subtitle' => 'International',
                'sort_order' => 17,
                'is_active' => true,
            ],
            [
                'page_slug' => 'who-we-are',
                'section_key' => 'faculty_header',
                'title' => 'Our Faculty',
                'subtitle' => 'Meet our distinguished faculty members committed to academic excellence',
                'sort_order' => 20,
                'is_active' => true,
            ],
            [
                'page_slug' => 'who-we-are',
                'section_key' => 'faculty',
                'title' => 'Main Campus Building',
                'subtitle' => 'Campus',
                'image' => 'Pix/3T0A0002.jpg',
                'sort_order' => 21,
                'is_active' => true,
            ],
            [
                'page_slug' => 'who-we-are',
                'section_key' => 'faculty',
                'title' => 'Library Facilities',
                'subtitle' => 'Academic',
                'image' => 'Pix/3T0A0013.jpg',
                'sort_order' => 22,
                'is_active' => true,
            ],
            [
                'page_slug' => 'who-we-are',
                'section_key' => 'faculty',
                'title' => 'Modern Classrooms',
                'subtitle' => 'Academic',
                'image' => 'Pix/3T0A0016.jpg',
                'sort_order' => 23,
                'is_active' => true,
            ],
            [
                'page_slug' => 'who-we-are',
                'section_key' => 'values_header',
                'title' => 'Our Values & Identity',
                'subtitle' => 'The principles that guide our mission',
                'sort_order' => 30,
                'is_active' => true,
            ],
            [
                'page_slug' => 'who-we-are',
                'section_key' => 'transform_future',
                'title' => 'Transform Your Future',
                'subtitle' => 'With University of Africa',
                'description' => 'We are more than a university; we are your partner in achieving excellence and transforming lives. Together, we will build a brighter future for Africa and beyond.',
                'sort_order' => 40,
                'is_active' => true,
            ],
        ];

        foreach ($visionMissionSections as $section) {
            AboutPageSection::create($section);
        }

        foreach ($whoWeAreSections as $section) {
            AboutPageSection::create($section);
        }
    }
}
